services:
  db:
    image: postgres:15-alpine
    container_name: bank_db_container
    environment:
      POSTGRES_DB: bank_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bank_network

  app:
    build: .
    container_name: bank_app_container
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bank_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - bank_network

networks:
  bank_network:
    driver: bridge

volumes:
  postgres_data: